'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabMain As UInteger = 1001
            Public Const cmdGroupRichFont As UInteger = 1002
            Public Const cmdRichFont As UInteger = 1003
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabMain As RibbonTab
        Public ReadOnly Property TabMain As RibbonTab
            Get
                Return _TabMain
            End Get
        End Property
        Private _GroupRichFont As RibbonGroup
        Public ReadOnly Property GroupRichFont As RibbonGroup
            Get
                Return _GroupRichFont
            End Get
        End Property
        Private _RichFont As RibbonFontControl
        Public ReadOnly Property RichFont As RibbonFontControl
            Get
                Return _RichFont
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabMain = New RibbonTab(_ribbon, Cmd.cmdTabMain)
            _GroupRichFont = New RibbonGroup(_ribbon, Cmd.cmdGroupRichFont)
            _RichFont = New RibbonFontControl(_ribbon, Cmd.cmdRichFont)
        End Sub

    End Class
End Namespace
