'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabMain As UInteger = 1011
            Public Const cmdGroupButtons As UInteger = 1013
            Public Const cmdButton As UInteger = 1001
            Public Const cmdToggleButton As UInteger = 1002
            Public Const cmdDropDown As UInteger = 1004
            Public Const cmdButtonDropA As UInteger = 1008
            Public Const cmdButtonDropB As UInteger = 1009
            Public Const cmdButtonDropC As UInteger = 1010
            Public Const cmdGroupCheckBox As UInteger = 1014
            Public Const cmdCheckBox As UInteger = 1003
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabMain As RibbonTab
        Public ReadOnly Property TabMain As RibbonTab
            Get
                Return _TabMain
            End Get
        End Property
        Private _GroupButtons As RibbonGroup
        Public ReadOnly Property GroupButtons As RibbonGroup
            Get
                Return _GroupButtons
            End Get
        End Property
        Private _Button As RibbonButton
        Public ReadOnly Property Button As RibbonButton
            Get
                Return _Button
            End Get
        End Property
        Private _ToggleButton As RibbonToggleButton
        Public ReadOnly Property ToggleButton As RibbonToggleButton
            Get
                Return _ToggleButton
            End Get
        End Property
        Private _DropDown As RibbonDropDownButton
        Public ReadOnly Property DropDown As RibbonDropDownButton
            Get
                Return _DropDown
            End Get
        End Property
        Private _ButtonDropA As RibbonButton
        Public ReadOnly Property ButtonDropA As RibbonButton
            Get
                Return _ButtonDropA
            End Get
        End Property
        Private _ButtonDropB As RibbonButton
        Public ReadOnly Property ButtonDropB As RibbonButton
            Get
                Return _ButtonDropB
            End Get
        End Property
        Private _ButtonDropC As RibbonButton
        Public ReadOnly Property ButtonDropC As RibbonButton
            Get
                Return _ButtonDropC
            End Get
        End Property
        Private _GroupCheckBox As RibbonGroup
        Public ReadOnly Property GroupCheckBox As RibbonGroup
            Get
                Return _GroupCheckBox
            End Get
        End Property
        Private _CheckBox As RibbonCheckBox
        Public ReadOnly Property CheckBox As RibbonCheckBox
            Get
                Return _CheckBox
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabMain = New RibbonTab(_ribbon, Cmd.cmdTabMain)
            _GroupButtons = New RibbonGroup(_ribbon, Cmd.cmdGroupButtons)
            _Button = New RibbonButton(_ribbon, Cmd.cmdButton)
            _ToggleButton = New RibbonToggleButton(_ribbon, Cmd.cmdToggleButton)
            _DropDown = New RibbonDropDownButton(_ribbon, Cmd.cmdDropDown)
            _ButtonDropA = New RibbonButton(_ribbon, Cmd.cmdButtonDropA)
            _ButtonDropB = New RibbonButton(_ribbon, Cmd.cmdButtonDropB)
            _ButtonDropC = New RibbonButton(_ribbon, Cmd.cmdButtonDropC)
            _GroupCheckBox = New RibbonGroup(_ribbon, Cmd.cmdGroupCheckBox)
            _CheckBox = New RibbonCheckBox(_ribbon, Cmd.cmdCheckBox)
        End Sub

    End Class
End Namespace
