'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabHome As UInteger = 1011
            Public Const cmdGroupParagraph As UInteger = 1010
            Public Const cmdDecreaseIndent As UInteger = 1001
            Public Const cmdIncreaseIndent As UInteger = 1002
            Public Const cmdStartList As UInteger = 1003
            Public Const cmdLineSpacing As UInteger = 1004
            Public Const cmdAlignLeft As UInteger = 1005
            Public Const cmdAlignCenter As UInteger = 1006
            Public Const cmdAlignRight As UInteger = 1007
            Public Const cmdJustify As UInteger = 1008
            Public Const cmdParagraph As UInteger = 1009
            Public Const cmdTabSpecialLayouts As UInteger = 2204
            Public Const cmdGroup1 As UInteger = 84
            Public Const cmdCombo1 As UInteger = 78
            Public Const cmdButton1 As UInteger = 80
            Public Const cmdCombo2 As UInteger = 79
            Public Const cmdButton2 As UInteger = 81
            Public Const cmdHidden1 As UInteger = 82
            Public Const cmdGroup2 As UInteger = 85
            Public Const cmdHidden2 As UInteger = 83
            Public Const cmdGroup3 As UInteger = 86
            Public Const cmdButtonLabel As UInteger = 87
            Public Const cmdGroup4 As UInteger = 88
            Public Const cmdGroup5 As UInteger = 89
            Public Const cmdButtonDate As UInteger = 90
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabHome As RibbonTab
        Public ReadOnly Property TabHome As RibbonTab
            Get
                Return _TabHome
            End Get
        End Property
        Private _GroupParagraph As RibbonGroup
        Public ReadOnly Property GroupParagraph As RibbonGroup
            Get
                Return _GroupParagraph
            End Get
        End Property
        Private _DecreaseIndent As RibbonButton
        Public ReadOnly Property DecreaseIndent As RibbonButton
            Get
                Return _DecreaseIndent
            End Get
        End Property
        Private _IncreaseIndent As RibbonButton
        Public ReadOnly Property IncreaseIndent As RibbonButton
            Get
                Return _IncreaseIndent
            End Get
        End Property
        Private _StartList As RibbonButton
        Public ReadOnly Property StartList As RibbonButton
            Get
                Return _StartList
            End Get
        End Property
        Private _LineSpacing As RibbonDropDownButton
        Public ReadOnly Property LineSpacing As RibbonDropDownButton
            Get
                Return _LineSpacing
            End Get
        End Property
        Private _AlignLeft As RibbonButton
        Public ReadOnly Property AlignLeft As RibbonButton
            Get
                Return _AlignLeft
            End Get
        End Property
        Private _AlignCenter As RibbonButton
        Public ReadOnly Property AlignCenter As RibbonButton
            Get
                Return _AlignCenter
            End Get
        End Property
        Private _AlignRight As RibbonButton
        Public ReadOnly Property AlignRight As RibbonButton
            Get
                Return _AlignRight
            End Get
        End Property
        Private _Justify As RibbonButton
        Public ReadOnly Property Justify As RibbonButton
            Get
                Return _Justify
            End Get
        End Property
        Private _Paragraph As RibbonButton
        Public ReadOnly Property Paragraph As RibbonButton
            Get
                Return _Paragraph
            End Get
        End Property
        Private _TabSpecialLayouts As RibbonTab
        Public ReadOnly Property TabSpecialLayouts As RibbonTab
            Get
                Return _TabSpecialLayouts
            End Get
        End Property
        Private _Group1 As RibbonGroup
        Public ReadOnly Property Group1 As RibbonGroup
            Get
                Return _Group1
            End Get
        End Property
        Private _Combo1 As RibbonComboBox
        Public ReadOnly Property Combo1 As RibbonComboBox
            Get
                Return _Combo1
            End Get
        End Property
        Private _Button1 As RibbonButton
        Public ReadOnly Property Button1 As RibbonButton
            Get
                Return _Button1
            End Get
        End Property
        Private _Combo2 As RibbonComboBox
        Public ReadOnly Property Combo2 As RibbonComboBox
            Get
                Return _Combo2
            End Get
        End Property
        Private _Button2 As RibbonButton
        Public ReadOnly Property Button2 As RibbonButton
            Get
                Return _Button2
            End Get
        End Property
        Private _Hidden1 As RibbonButton
        Public ReadOnly Property Hidden1 As RibbonButton
            Get
                Return _Hidden1
            End Get
        End Property
        Private _Group2 As RibbonGroup
        Public ReadOnly Property Group2 As RibbonGroup
            Get
                Return _Group2
            End Get
        End Property
        Private _Hidden2 As RibbonButton
        Public ReadOnly Property Hidden2 As RibbonButton
            Get
                Return _Hidden2
            End Get
        End Property
        Private _Group3 As RibbonGroup
        Public ReadOnly Property Group3 As RibbonGroup
            Get
                Return _Group3
            End Get
        End Property
        Private _ButtonLabel As RibbonButton
        Public ReadOnly Property ButtonLabel As RibbonButton
            Get
                Return _ButtonLabel
            End Get
        End Property
        Private _Group4 As RibbonGroup
        Public ReadOnly Property Group4 As RibbonGroup
            Get
                Return _Group4
            End Get
        End Property
        Private _Group5 As RibbonGroup
        Public ReadOnly Property Group5 As RibbonGroup
            Get
                Return _Group5
            End Get
        End Property
        Private _ButtonDate As RibbonButton
        Public ReadOnly Property ButtonDate As RibbonButton
            Get
                Return _ButtonDate
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabHome = New RibbonTab(_ribbon, Cmd.cmdTabHome)
            _GroupParagraph = New RibbonGroup(_ribbon, Cmd.cmdGroupParagraph)
            _DecreaseIndent = New RibbonButton(_ribbon, Cmd.cmdDecreaseIndent)
            _IncreaseIndent = New RibbonButton(_ribbon, Cmd.cmdIncreaseIndent)
            _StartList = New RibbonButton(_ribbon, Cmd.cmdStartList)
            _LineSpacing = New RibbonDropDownButton(_ribbon, Cmd.cmdLineSpacing)
            _AlignLeft = New RibbonButton(_ribbon, Cmd.cmdAlignLeft)
            _AlignCenter = New RibbonButton(_ribbon, Cmd.cmdAlignCenter)
            _AlignRight = New RibbonButton(_ribbon, Cmd.cmdAlignRight)
            _Justify = New RibbonButton(_ribbon, Cmd.cmdJustify)
            _Paragraph = New RibbonButton(_ribbon, Cmd.cmdParagraph)
            _TabSpecialLayouts = New RibbonTab(_ribbon, Cmd.cmdTabSpecialLayouts)
            _Group1 = New RibbonGroup(_ribbon, Cmd.cmdGroup1)
            _Combo1 = New RibbonComboBox(_ribbon, Cmd.cmdCombo1)
            _Button1 = New RibbonButton(_ribbon, Cmd.cmdButton1)
            _Combo2 = New RibbonComboBox(_ribbon, Cmd.cmdCombo2)
            _Button2 = New RibbonButton(_ribbon, Cmd.cmdButton2)
            _Hidden1 = New RibbonButton(_ribbon, Cmd.cmdHidden1)
            _Group2 = New RibbonGroup(_ribbon, Cmd.cmdGroup2)
            _Hidden2 = New RibbonButton(_ribbon, Cmd.cmdHidden2)
            _Group3 = New RibbonGroup(_ribbon, Cmd.cmdGroup3)
            _ButtonLabel = New RibbonButton(_ribbon, Cmd.cmdButtonLabel)
            _Group4 = New RibbonGroup(_ribbon, Cmd.cmdGroup4)
            _Group5 = New RibbonGroup(_ribbon, Cmd.cmdGroup5)
            _ButtonDate = New RibbonButton(_ribbon, Cmd.cmdButtonDate)
        End Sub

    End Class
End Namespace
