'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabHome As UInteger = 1011
            Public Const cmdGroupParagraph As UInteger = 1010
            Public Const cmdDecreaseIndent As UInteger = 1001
            Public Const cmdIncreaseIndent As UInteger = 1002
            Public Const cmdStartList As UInteger = 1003
            Public Const cmdLineSpacing As UInteger = 1004
            Public Const cmdAlignLeft As UInteger = 1005
            Public Const cmdAlignCenter As UInteger = 1006
            Public Const cmdAlignRight As UInteger = 1007
            Public Const cmdJustify As UInteger = 1008
            Public Const cmdParagraph As UInteger = 1009
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabHome As RibbonTab
        Public ReadOnly Property TabHome As RibbonTab
            Get
                Return _TabHome
            End Get
        End Property
        Private _GroupParagraph As RibbonGroup
        Public ReadOnly Property GroupParagraph As RibbonGroup
            Get
                Return _GroupParagraph
            End Get
        End Property
        Private _DecreaseIndent As RibbonButton
        Public ReadOnly Property DecreaseIndent As RibbonButton
            Get
                Return _DecreaseIndent
            End Get
        End Property
        Private _IncreaseIndent As RibbonButton
        Public ReadOnly Property IncreaseIndent As RibbonButton
            Get
                Return _IncreaseIndent
            End Get
        End Property
        Private _StartList As RibbonButton
        Public ReadOnly Property StartList As RibbonButton
            Get
                Return _StartList
            End Get
        End Property
        Private _LineSpacing As RibbonDropDownButton
        Public ReadOnly Property LineSpacing As RibbonDropDownButton
            Get
                Return _LineSpacing
            End Get
        End Property
        Private _AlignLeft As RibbonButton
        Public ReadOnly Property AlignLeft As RibbonButton
            Get
                Return _AlignLeft
            End Get
        End Property
        Private _AlignCenter As RibbonButton
        Public ReadOnly Property AlignCenter As RibbonButton
            Get
                Return _AlignCenter
            End Get
        End Property
        Private _AlignRight As RibbonButton
        Public ReadOnly Property AlignRight As RibbonButton
            Get
                Return _AlignRight
            End Get
        End Property
        Private _Justify As RibbonButton
        Public ReadOnly Property Justify As RibbonButton
            Get
                Return _Justify
            End Get
        End Property
        Private _Paragraph As RibbonButton
        Public ReadOnly Property Paragraph As RibbonButton
            Get
                Return _Paragraph
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabHome = New RibbonTab(_ribbon, Cmd.cmdTabHome)
            _GroupParagraph = New RibbonGroup(_ribbon, Cmd.cmdGroupParagraph)
            _DecreaseIndent = New RibbonButton(_ribbon, Cmd.cmdDecreaseIndent)
            _IncreaseIndent = New RibbonButton(_ribbon, Cmd.cmdIncreaseIndent)
            _StartList = New RibbonButton(_ribbon, Cmd.cmdStartList)
            _LineSpacing = New RibbonDropDownButton(_ribbon, Cmd.cmdLineSpacing)
            _AlignLeft = New RibbonButton(_ribbon, Cmd.cmdAlignLeft)
            _AlignCenter = New RibbonButton(_ribbon, Cmd.cmdAlignCenter)
            _AlignRight = New RibbonButton(_ribbon, Cmd.cmdAlignRight)
            _Justify = New RibbonButton(_ribbon, Cmd.cmdJustify)
            _Paragraph = New RibbonButton(_ribbon, Cmd.cmdParagraph)
        End Sub

    End Class
End Namespace
