'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabDrop As UInteger = 1014
            Public Const cmdGroupDrop As UInteger = 1015
            Public Const cmdButtonDropA As UInteger = 1008
            Public Const cmdButtonDropB As UInteger = 1009
            Public Const cmdButtonDropC As UInteger = 1010
            Public Const cmdButtonDropD As UInteger = 1011
            Public Const cmdButtonDropE As UInteger = 1012
            Public Const cmdButtonDropF As UInteger = 1013
            Public Const cmdGroupMore As UInteger = 1017
            Public Const cmdComboBox1 As UInteger = 1018
            Public Const cmdComboBox2 As UInteger = 1019
            Public Const cmdTabSecond As UInteger = 1020
            Public Const cmdGroupSecond As UInteger = 1021
            Public Const cmdComboBox3 As UInteger = 1022
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabDrop As RibbonTab
        Public ReadOnly Property TabDrop As RibbonTab
            Get
                Return _TabDrop
            End Get
        End Property
        Private _GroupDrop As RibbonGroup
        Public ReadOnly Property GroupDrop As RibbonGroup
            Get
                Return _GroupDrop
            End Get
        End Property
        Private _ButtonDropA As RibbonButton
        Public ReadOnly Property ButtonDropA As RibbonButton
            Get
                Return _ButtonDropA
            End Get
        End Property
        Private _ButtonDropB As RibbonButton
        Public ReadOnly Property ButtonDropB As RibbonButton
            Get
                Return _ButtonDropB
            End Get
        End Property
        Private _ButtonDropC As RibbonButton
        Public ReadOnly Property ButtonDropC As RibbonButton
            Get
                Return _ButtonDropC
            End Get
        End Property
        Private _ButtonDropD As RibbonButton
        Public ReadOnly Property ButtonDropD As RibbonButton
            Get
                Return _ButtonDropD
            End Get
        End Property
        Private _ButtonDropE As RibbonButton
        Public ReadOnly Property ButtonDropE As RibbonButton
            Get
                Return _ButtonDropE
            End Get
        End Property
        Private _ButtonDropF As RibbonButton
        Public ReadOnly Property ButtonDropF As RibbonButton
            Get
                Return _ButtonDropF
            End Get
        End Property
        Private _GroupMore As RibbonGroup
        Public ReadOnly Property GroupMore As RibbonGroup
            Get
                Return _GroupMore
            End Get
        End Property
        Private _ComboBox1 As RibbonComboBox
        Public ReadOnly Property ComboBox1 As RibbonComboBox
            Get
                Return _ComboBox1
            End Get
        End Property
        Private _ComboBox2 As RibbonComboBox
        Public ReadOnly Property ComboBox2 As RibbonComboBox
            Get
                Return _ComboBox2
            End Get
        End Property
        Private _TabSecond As RibbonTab
        Public ReadOnly Property TabSecond As RibbonTab
            Get
                Return _TabSecond
            End Get
        End Property
        Private _GroupSecond As RibbonGroup
        Public ReadOnly Property GroupSecond As RibbonGroup
            Get
                Return _GroupSecond
            End Get
        End Property
        Private _ComboBox3 As RibbonComboBox
        Public ReadOnly Property ComboBox3 As RibbonComboBox
            Get
                Return _ComboBox3
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabDrop = New RibbonTab(_ribbon, Cmd.cmdTabDrop)
            _GroupDrop = New RibbonGroup(_ribbon, Cmd.cmdGroupDrop)
            _ButtonDropA = New RibbonButton(_ribbon, Cmd.cmdButtonDropA)
            _ButtonDropB = New RibbonButton(_ribbon, Cmd.cmdButtonDropB)
            _ButtonDropC = New RibbonButton(_ribbon, Cmd.cmdButtonDropC)
            _ButtonDropD = New RibbonButton(_ribbon, Cmd.cmdButtonDropD)
            _ButtonDropE = New RibbonButton(_ribbon, Cmd.cmdButtonDropE)
            _ButtonDropF = New RibbonButton(_ribbon, Cmd.cmdButtonDropF)
            _GroupMore = New RibbonGroup(_ribbon, Cmd.cmdGroupMore)
            _ComboBox1 = New RibbonComboBox(_ribbon, Cmd.cmdComboBox1)
            _ComboBox2 = New RibbonComboBox(_ribbon, Cmd.cmdComboBox2)
            _TabSecond = New RibbonTab(_ribbon, Cmd.cmdTabSecond)
            _GroupSecond = New RibbonGroup(_ribbon, Cmd.cmdGroupSecond)
            _ComboBox3 = New RibbonComboBox(_ribbon, Cmd.cmdComboBox3)
        End Sub

    End Class
End Namespace
