'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdFontControl As UInteger = 1006
            Public Const cmdDropDownColorPicker As UInteger = 1007
            Public Const cmdButtonNew As UInteger = 1001
            Public Const cmdButtonOpen As UInteger = 1002
            Public Const cmdButtonSave As UInteger = 1003
            Public Const cmdContextMap As UInteger = 1005
        End Class

        ' ContextPopup CommandName
        Public Const cmdContextMap As UInteger = Cmd.cmdContextMap

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _FontControl As RibbonFontControl
        Public ReadOnly Property FontControl As RibbonFontControl
            Get
                Return _FontControl
            End Get
        End Property
        Private _DropDownColorPicker As RibbonDropDownColorPicker
        Public ReadOnly Property DropDownColorPicker As RibbonDropDownColorPicker
            Get
                Return _DropDownColorPicker
            End Get
        End Property
        Private _ButtonNew As RibbonButton
        Public ReadOnly Property ButtonNew As RibbonButton
            Get
                Return _ButtonNew
            End Get
        End Property
        Private _ButtonOpen As RibbonButton
        Public ReadOnly Property ButtonOpen As RibbonButton
            Get
                Return _ButtonOpen
            End Get
        End Property
        Private _ButtonSave As RibbonButton
        Public ReadOnly Property ButtonSave As RibbonButton
            Get
                Return _ButtonSave
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _FontControl = New RibbonFontControl(_ribbon, Cmd.cmdFontControl)
            _DropDownColorPicker = New RibbonDropDownColorPicker(_ribbon, Cmd.cmdDropDownColorPicker)
            _ButtonNew = New RibbonButton(_ribbon, Cmd.cmdButtonNew)
            _ButtonOpen = New RibbonButton(_ribbon, Cmd.cmdButtonOpen)
            _ButtonSave = New RibbonButton(_ribbon, Cmd.cmdButtonSave)
        End Sub

    End Class
End Namespace
