'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabDrop As UInteger = 1012
            Public Const cmdGroupDrop As UInteger = 1015
            Public Const cmdButtonDropA As UInteger = 1008
            Public Const cmdButtonDropB As UInteger = 1009
            Public Const cmdButtonDropC As UInteger = 1010
            Public Const cmdGroupMore As UInteger = 1017
            Public Const cmdSpinner As UInteger = 1018
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabDrop As RibbonTab
        Public ReadOnly Property TabDrop As RibbonTab
            Get
                Return _TabDrop
            End Get
        End Property
        Private _GroupDrop As RibbonGroup
        Public ReadOnly Property GroupDrop As RibbonGroup
            Get
                Return _GroupDrop
            End Get
        End Property
        Private _ButtonDropA As RibbonButton
        Public ReadOnly Property ButtonDropA As RibbonButton
            Get
                Return _ButtonDropA
            End Get
        End Property
        Private _ButtonDropB As RibbonButton
        Public ReadOnly Property ButtonDropB As RibbonButton
            Get
                Return _ButtonDropB
            End Get
        End Property
        Private _ButtonDropC As RibbonButton
        Public ReadOnly Property ButtonDropC As RibbonButton
            Get
                Return _ButtonDropC
            End Get
        End Property
        Private _GroupMore As RibbonGroup
        Public ReadOnly Property GroupMore As RibbonGroup
            Get
                Return _GroupMore
            End Get
        End Property
        Private _Spinner As RibbonSpinner
        Public ReadOnly Property Spinner As RibbonSpinner
            Get
                Return _Spinner
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabDrop = New RibbonTab(_ribbon, Cmd.cmdTabDrop)
            _GroupDrop = New RibbonGroup(_ribbon, Cmd.cmdGroupDrop)
            _ButtonDropA = New RibbonButton(_ribbon, Cmd.cmdButtonDropA)
            _ButtonDropB = New RibbonButton(_ribbon, Cmd.cmdButtonDropB)
            _ButtonDropC = New RibbonButton(_ribbon, Cmd.cmdButtonDropC)
            _GroupMore = New RibbonGroup(_ribbon, Cmd.cmdGroupMore)
            _Spinner = New RibbonSpinner(_ribbon, Cmd.cmdSpinner)
        End Sub

    End Class
End Namespace
