'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdMenuGroupFile As UInteger = 1005
            Public Const cmdButtonNew As UInteger = 1001
            Public Const cmdButtonOpen As UInteger = 1002
            Public Const cmdButtonSave As UInteger = 1003
            Public Const cmdDropDownButton As UInteger = 1007
            Public Const cmdButtonDropA As UInteger = 1008
            Public Const cmdButtonDropB As UInteger = 1009
            Public Const cmdButtonDropC As UInteger = 1010
            Public Const cmdMenuGroupExit As UInteger = 1006
            Public Const cmdButtonExit As UInteger = 1004
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _MenuGroupFile As RibbonMenuGroup
        Public ReadOnly Property MenuGroupFile As RibbonMenuGroup
            Get
                Return _MenuGroupFile
            End Get
        End Property
        Private _ButtonNew As RibbonButton
        Public ReadOnly Property ButtonNew As RibbonButton
            Get
                Return _ButtonNew
            End Get
        End Property
        Private _ButtonOpen As RibbonButton
        Public ReadOnly Property ButtonOpen As RibbonButton
            Get
                Return _ButtonOpen
            End Get
        End Property
        Private _ButtonSave As RibbonButton
        Public ReadOnly Property ButtonSave As RibbonButton
            Get
                Return _ButtonSave
            End Get
        End Property
        Private _DropDownButton As RibbonDropDownButton
        Public ReadOnly Property DropDownButton As RibbonDropDownButton
            Get
                Return _DropDownButton
            End Get
        End Property
        Private _ButtonDropA As RibbonButton
        Public ReadOnly Property ButtonDropA As RibbonButton
            Get
                Return _ButtonDropA
            End Get
        End Property
        Private _ButtonDropB As RibbonButton
        Public ReadOnly Property ButtonDropB As RibbonButton
            Get
                Return _ButtonDropB
            End Get
        End Property
        Private _ButtonDropC As RibbonButton
        Public ReadOnly Property ButtonDropC As RibbonButton
            Get
                Return _ButtonDropC
            End Get
        End Property
        Private _MenuGroupExit As RibbonMenuGroup
        Public ReadOnly Property MenuGroupExit As RibbonMenuGroup
            Get
                Return _MenuGroupExit
            End Get
        End Property
        Private _ButtonExit As RibbonButton
        Public ReadOnly Property ButtonExit As RibbonButton
            Get
                Return _ButtonExit
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _MenuGroupFile = New RibbonMenuGroup(_ribbon, Cmd.cmdMenuGroupFile)
            _ButtonNew = New RibbonButton(_ribbon, Cmd.cmdButtonNew)
            _ButtonOpen = New RibbonButton(_ribbon, Cmd.cmdButtonOpen)
            _ButtonSave = New RibbonButton(_ribbon, Cmd.cmdButtonSave)
            _DropDownButton = New RibbonDropDownButton(_ribbon, Cmd.cmdDropDownButton)
            _ButtonDropA = New RibbonButton(_ribbon, Cmd.cmdButtonDropA)
            _ButtonDropB = New RibbonButton(_ribbon, Cmd.cmdButtonDropB)
            _ButtonDropC = New RibbonButton(_ribbon, Cmd.cmdButtonDropC)
            _MenuGroupExit = New RibbonMenuGroup(_ribbon, Cmd.cmdMenuGroupExit)
            _ButtonExit = New RibbonButton(_ribbon, Cmd.cmdButtonExit)
        End Sub

    End Class
End Namespace
