'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabMain As UInteger = 1000
            Public Const cmdGroupDropDownGallery As UInteger = 1001
            Public Const cmdDropDownGallery As UInteger = 1002
            Public Const cmdCommandSpace As UInteger = 1003
            Public Const cmdGroupSplitButtonGallery As UInteger = 1004
            Public Const cmdSplitButtonGallery As UInteger = 1005
            Public Const cmdGroupInRibbonGallery As UInteger = 1006
            Public Const cmdInRibbonGallery As UInteger = 1007
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabMain As RibbonTab
        Public ReadOnly Property TabMain As RibbonTab
            Get
                Return _TabMain
            End Get
        End Property
        Private _GroupDropDownGallery As RibbonGroup
        Public ReadOnly Property GroupDropDownGallery As RibbonGroup
            Get
                Return _GroupDropDownGallery
            End Get
        End Property
        Private _DropDownGallery As RibbonDropDownGallery
        Public ReadOnly Property DropDownGallery As RibbonDropDownGallery
            Get
                Return _DropDownGallery
            End Get
        End Property
        Private _CommandSpace As RibbonButton
        Public ReadOnly Property CommandSpace As RibbonButton
            Get
                Return _CommandSpace
            End Get
        End Property
        Private _GroupSplitButtonGallery As RibbonGroup
        Public ReadOnly Property GroupSplitButtonGallery As RibbonGroup
            Get
                Return _GroupSplitButtonGallery
            End Get
        End Property
        Private _SplitButtonGallery As RibbonSplitButtonGallery
        Public ReadOnly Property SplitButtonGallery As RibbonSplitButtonGallery
            Get
                Return _SplitButtonGallery
            End Get
        End Property
        Private _GroupInRibbonGallery As RibbonGroup
        Public ReadOnly Property GroupInRibbonGallery As RibbonGroup
            Get
                Return _GroupInRibbonGallery
            End Get
        End Property
        Private _InRibbonGallery As RibbonInRibbonGallery
        Public ReadOnly Property InRibbonGallery As RibbonInRibbonGallery
            Get
                Return _InRibbonGallery
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabMain = New RibbonTab(_ribbon, Cmd.cmdTabMain)
            _GroupDropDownGallery = New RibbonGroup(_ribbon, Cmd.cmdGroupDropDownGallery)
            _DropDownGallery = New RibbonDropDownGallery(_ribbon, Cmd.cmdDropDownGallery)
            _CommandSpace = New RibbonButton(_ribbon, Cmd.cmdCommandSpace)
            _GroupSplitButtonGallery = New RibbonGroup(_ribbon, Cmd.cmdGroupSplitButtonGallery)
            _SplitButtonGallery = New RibbonSplitButtonGallery(_ribbon, Cmd.cmdSplitButtonGallery)
            _GroupInRibbonGallery = New RibbonGroup(_ribbon, Cmd.cmdGroupInRibbonGallery)
            _InRibbonGallery = New RibbonInRibbonGallery(_ribbon, Cmd.cmdInRibbonGallery)
        End Sub

    End Class
End Namespace
