'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdHelpButton As UInteger = 1016
            Public Const cmdTabMain As UInteger = 1011
            Public Const cmdGroupFileActions As UInteger = 1013
            Public Const cmdButtonNew As UInteger = 1001
            Public Const cmdButtonOpen As UInteger = 1002
            Public Const cmdButtonSave As UInteger = 1003
            Public Const cmdGroupExit As UInteger = 1014
            Public Const cmdButtonExit As UInteger = 1004
            Public Const cmdTabDrop As UInteger = 1012
            Public Const cmdGroupDrop As UInteger = 1015
            Public Const cmdButtonDropA As UInteger = 1008
            Public Const cmdButtonDropB As UInteger = 1009
            Public Const cmdButtonDropC As UInteger = 1010
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _HelpButton As RibbonHelpButton
        Public ReadOnly Property HelpButton As RibbonHelpButton
            Get
                Return _HelpButton
            End Get
        End Property
        Private _TabMain As RibbonTab
        Public ReadOnly Property TabMain As RibbonTab
            Get
                Return _TabMain
            End Get
        End Property
        Private _GroupFileActions As RibbonGroup
        Public ReadOnly Property GroupFileActions As RibbonGroup
            Get
                Return _GroupFileActions
            End Get
        End Property
        Private _ButtonNew As RibbonButton
        Public ReadOnly Property ButtonNew As RibbonButton
            Get
                Return _ButtonNew
            End Get
        End Property
        Private _ButtonOpen As RibbonButton
        Public ReadOnly Property ButtonOpen As RibbonButton
            Get
                Return _ButtonOpen
            End Get
        End Property
        Private _ButtonSave As RibbonButton
        Public ReadOnly Property ButtonSave As RibbonButton
            Get
                Return _ButtonSave
            End Get
        End Property
        Private _GroupExit As RibbonGroup
        Public ReadOnly Property GroupExit As RibbonGroup
            Get
                Return _GroupExit
            End Get
        End Property
        Private _ButtonExit As RibbonButton
        Public ReadOnly Property ButtonExit As RibbonButton
            Get
                Return _ButtonExit
            End Get
        End Property
        Private _TabDrop As RibbonTab
        Public ReadOnly Property TabDrop As RibbonTab
            Get
                Return _TabDrop
            End Get
        End Property
        Private _GroupDrop As RibbonGroup
        Public ReadOnly Property GroupDrop As RibbonGroup
            Get
                Return _GroupDrop
            End Get
        End Property
        Private _ButtonDropA As RibbonButton
        Public ReadOnly Property ButtonDropA As RibbonButton
            Get
                Return _ButtonDropA
            End Get
        End Property
        Private _ButtonDropB As RibbonButton
        Public ReadOnly Property ButtonDropB As RibbonButton
            Get
                Return _ButtonDropB
            End Get
        End Property
        Private _ButtonDropC As RibbonButton
        Public ReadOnly Property ButtonDropC As RibbonButton
            Get
                Return _ButtonDropC
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _HelpButton = New RibbonHelpButton(_ribbon, Cmd.cmdHelpButton)
            _TabMain = New RibbonTab(_ribbon, Cmd.cmdTabMain)
            _GroupFileActions = New RibbonGroup(_ribbon, Cmd.cmdGroupFileActions)
            _ButtonNew = New RibbonButton(_ribbon, Cmd.cmdButtonNew)
            _ButtonOpen = New RibbonButton(_ribbon, Cmd.cmdButtonOpen)
            _ButtonSave = New RibbonButton(_ribbon, Cmd.cmdButtonSave)
            _GroupExit = New RibbonGroup(_ribbon, Cmd.cmdGroupExit)
            _ButtonExit = New RibbonButton(_ribbon, Cmd.cmdButtonExit)
            _TabDrop = New RibbonTab(_ribbon, Cmd.cmdTabDrop)
            _GroupDrop = New RibbonGroup(_ribbon, Cmd.cmdGroupDrop)
            _ButtonDropA = New RibbonButton(_ribbon, Cmd.cmdButtonDropA)
            _ButtonDropB = New RibbonButton(_ribbon, Cmd.cmdButtonDropB)
            _ButtonDropC = New RibbonButton(_ribbon, Cmd.cmdButtonDropC)
        End Sub

    End Class
End Namespace
