'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTab As UInteger = 1012
            Public Const cmdGroup As UInteger = 1015
            Public Const cmdButtonOne As UInteger = 1008
            Public Const cmdButtonTwo As UInteger = 1009
            Public Const cmdButtonThree As UInteger = 1010
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _Tab As RibbonTab
        Public ReadOnly Property Tab As RibbonTab
            Get
                Return _Tab
            End Get
        End Property
        Private _Group As RibbonGroup
        Public ReadOnly Property Group As RibbonGroup
            Get
                Return _Group
            End Get
        End Property
        Private _ButtonOne As RibbonButton
        Public ReadOnly Property ButtonOne As RibbonButton
            Get
                Return _ButtonOne
            End Get
        End Property
        Private _ButtonTwo As RibbonButton
        Public ReadOnly Property ButtonTwo As RibbonButton
            Get
                Return _ButtonTwo
            End Get
        End Property
        Private _ButtonThree As RibbonButton
        Public ReadOnly Property ButtonThree As RibbonButton
            Get
                Return _ButtonThree
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _Tab = New RibbonTab(_ribbon, Cmd.cmdTab)
            _Group = New RibbonGroup(_ribbon, Cmd.cmdGroup)
            _ButtonOne = New RibbonButton(_ribbon, Cmd.cmdButtonOne)
            _ButtonTwo = New RibbonButton(_ribbon, Cmd.cmdButtonTwo)
            _ButtonThree = New RibbonButton(_ribbon, Cmd.cmdButtonThree)
        End Sub

    End Class
End Namespace
