'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTabGroupTableTools As UInteger = 1003
            Public Const cmdTabDesign As UInteger = 1004
            Public Const cmdGroupDesign As UInteger = 1006
            Public Const cmdButtonDesign1 As UInteger = 1010
            Public Const cmdButtonDesign2 As UInteger = 1011
            Public Const cmdButtonDesign3 As UInteger = 1012
            Public Const cmdTabLayout As UInteger = 1005
            Public Const cmdGroupLayout As UInteger = 1007
            Public Const cmdButtonLayout1 As UInteger = 1013
            Public Const cmdButtonLayout2 As UInteger = 1014
            Public Const cmdTabMain As UInteger = 1001
            Public Const cmdGroupMain As UInteger = 1002
            Public Const cmdButtonSelect As UInteger = 1008
            Public Const cmdButtonUnselect As UInteger = 1009
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _TabGroupTableTools As RibbonTabGroup
        Public ReadOnly Property TabGroupTableTools As RibbonTabGroup
            Get
                Return _TabGroupTableTools
            End Get
        End Property
        Private _TabDesign As RibbonTab
        Public ReadOnly Property TabDesign As RibbonTab
            Get
                Return _TabDesign
            End Get
        End Property
        Private _GroupDesign As RibbonGroup
        Public ReadOnly Property GroupDesign As RibbonGroup
            Get
                Return _GroupDesign
            End Get
        End Property
        Private _ButtonDesign1 As RibbonButton
        Public ReadOnly Property ButtonDesign1 As RibbonButton
            Get
                Return _ButtonDesign1
            End Get
        End Property
        Private _ButtonDesign2 As RibbonButton
        Public ReadOnly Property ButtonDesign2 As RibbonButton
            Get
                Return _ButtonDesign2
            End Get
        End Property
        Private _ButtonDesign3 As RibbonButton
        Public ReadOnly Property ButtonDesign3 As RibbonButton
            Get
                Return _ButtonDesign3
            End Get
        End Property
        Private _TabLayout As RibbonTab
        Public ReadOnly Property TabLayout As RibbonTab
            Get
                Return _TabLayout
            End Get
        End Property
        Private _GroupLayout As RibbonGroup
        Public ReadOnly Property GroupLayout As RibbonGroup
            Get
                Return _GroupLayout
            End Get
        End Property
        Private _ButtonLayout1 As RibbonButton
        Public ReadOnly Property ButtonLayout1 As RibbonButton
            Get
                Return _ButtonLayout1
            End Get
        End Property
        Private _ButtonLayout2 As RibbonButton
        Public ReadOnly Property ButtonLayout2 As RibbonButton
            Get
                Return _ButtonLayout2
            End Get
        End Property
        Private _TabMain As RibbonTab
        Public ReadOnly Property TabMain As RibbonTab
            Get
                Return _TabMain
            End Get
        End Property
        Private _GroupMain As RibbonGroup
        Public ReadOnly Property GroupMain As RibbonGroup
            Get
                Return _GroupMain
            End Get
        End Property
        Private _ButtonSelect As RibbonButton
        Public ReadOnly Property ButtonSelect As RibbonButton
            Get
                Return _ButtonSelect
            End Get
        End Property
        Private _ButtonUnselect As RibbonButton
        Public ReadOnly Property ButtonUnselect As RibbonButton
            Get
                Return _ButtonUnselect
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _TabGroupTableTools = New RibbonTabGroup(_ribbon, Cmd.cmdTabGroupTableTools)
            _TabDesign = New RibbonTab(_ribbon, Cmd.cmdTabDesign)
            _GroupDesign = New RibbonGroup(_ribbon, Cmd.cmdGroupDesign)
            _ButtonDesign1 = New RibbonButton(_ribbon, Cmd.cmdButtonDesign1)
            _ButtonDesign2 = New RibbonButton(_ribbon, Cmd.cmdButtonDesign2)
            _ButtonDesign3 = New RibbonButton(_ribbon, Cmd.cmdButtonDesign3)
            _TabLayout = New RibbonTab(_ribbon, Cmd.cmdTabLayout)
            _GroupLayout = New RibbonGroup(_ribbon, Cmd.cmdGroupLayout)
            _ButtonLayout1 = New RibbonButton(_ribbon, Cmd.cmdButtonLayout1)
            _ButtonLayout2 = New RibbonButton(_ribbon, Cmd.cmdButtonLayout2)
            _TabMain = New RibbonTab(_ribbon, Cmd.cmdTabMain)
            _GroupMain = New RibbonGroup(_ribbon, Cmd.cmdGroupMain)
            _ButtonSelect = New RibbonButton(_ribbon, Cmd.cmdButtonSelect)
            _ButtonUnselect = New RibbonButton(_ribbon, Cmd.cmdButtonUnselect)
        End Sub

    End Class
End Namespace
