'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System

Namespace Global.WinForms.Ribbon
    Partial Class RibbonItems
        Private Class Cmd
            Public Const cmdTab As UInteger = 999
            Public Const cmdButtonsGroup As UInteger = 1000
            Public Const cmdButtonListColors As UInteger = 1006
            Public Const cmdDropDownColorPickerGroup As UInteger = 1001
            Public Const cmdDropDownColorPickerThemeColors As UInteger = 1002
            Public Const cmdDropDownColorPickerStandardColors As UInteger = 1003
            Public Const cmdDropDownColorPickerHighlightColors As UInteger = 1004
        End Class

        ' ContextPopup CommandName

        Private _ribbon As RibbonStrip
        Public ReadOnly Property Ribbon As RibbonStrip
            Get
                Return _ribbon
            End Get
        End Property
        Private _Tab As RibbonTab
        Public ReadOnly Property Tab As RibbonTab
            Get
                Return _Tab
            End Get
        End Property
        Private _ButtonsGroup As RibbonGroup
        Public ReadOnly Property ButtonsGroup As RibbonGroup
            Get
                Return _ButtonsGroup
            End Get
        End Property
        Private _ButtonListColors As RibbonButton
        Public ReadOnly Property ButtonListColors As RibbonButton
            Get
                Return _ButtonListColors
            End Get
        End Property
        Private _DropDownColorPickerGroup As RibbonGroup
        Public ReadOnly Property DropDownColorPickerGroup As RibbonGroup
            Get
                Return _DropDownColorPickerGroup
            End Get
        End Property
        Private _DropDownColorPickerThemeColors As RibbonDropDownColorPicker
        Public ReadOnly Property DropDownColorPickerThemeColors As RibbonDropDownColorPicker
            Get
                Return _DropDownColorPickerThemeColors
            End Get
        End Property
        Private _DropDownColorPickerStandardColors As RibbonDropDownColorPicker
        Public ReadOnly Property DropDownColorPickerStandardColors As RibbonDropDownColorPicker
            Get
                Return _DropDownColorPickerStandardColors
            End Get
        End Property
        Private _DropDownColorPickerHighlightColors As RibbonDropDownColorPicker
        Public ReadOnly Property DropDownColorPickerHighlightColors As RibbonDropDownColorPicker
            Get
                Return _DropDownColorPickerHighlightColors
            End Get
        End Property

        Public Sub New(ByVal ribbon As RibbonStrip)
            If ribbon Is Nothing Then
                Throw New ArgumentNullException(NameOf(ribbon), "Parameter is Nothing")
            End If
            _ribbon = ribbon
            _Tab = New RibbonTab(_ribbon, Cmd.cmdTab)
            _ButtonsGroup = New RibbonGroup(_ribbon, Cmd.cmdButtonsGroup)
            _ButtonListColors = New RibbonButton(_ribbon, Cmd.cmdButtonListColors)
            _DropDownColorPickerGroup = New RibbonGroup(_ribbon, Cmd.cmdDropDownColorPickerGroup)
            _DropDownColorPickerThemeColors = New RibbonDropDownColorPicker(_ribbon, Cmd.cmdDropDownColorPickerThemeColors)
            _DropDownColorPickerStandardColors = New RibbonDropDownColorPicker(_ribbon, Cmd.cmdDropDownColorPickerStandardColors)
            _DropDownColorPickerHighlightColors = New RibbonDropDownColorPicker(_ribbon, Cmd.cmdDropDownColorPickerHighlightColors)
        End Sub

    End Class
End Namespace
